include("$PROGDIR/GlobalFunctions/_includes.jl")
include("WC_DEFunctions.jl")
include("WC_Functions.jl")
include("WC_Structures.jl")
include("WC_WindowsRunFunc.jl")
include("WC_Setup.jl")
include("WC_TrialFunc.jl")
